### ISSUE TITLE
AutoTokenizer 관련 issue

### ISSUE THREAD

**Issue by KKang29** [bab2min/kiwi-farm#2]
안녕하세요, 
먼저, 좋은 형태소 분석기와, Tokenizer 등 오픈소스로 열어주셔서 감사합니다. 항상 잘 사용하고 있습니다.

관련 이슈가 있어서 말씀드립니다.

from transformers import (
    AutoTokenizer, 
    AutoModelForMaskedLM, 
)
import kiwipiepy.transformers_addon
#### 기존의 transformers 코드를 그대로 사용할 수 있다.

tokenizer = AutoTokenizer.from_pretrained('kiwi-farm/roberta-base-32k')
model = AutoModelForMaskedLM.from_pretrained('kiwi-farm/roberta-base-32k')

---------------------------------------------------------------------------

KeyError: 'added_tokens'

에러가 발생합니다. OS 등 로컬환경 문제인지, 패키지가 업데이트 되면서 꼬인건지 판단이 어렵네요.

OS: Ubuntu
Python 3.8.10
kiwipiepy == 0.16.2
transformers == 4.36.2

**Comment by bab2min** [comment]
안녕하세요 @KKang29 님, 오류 제보 감사드립니다.
kiwipiepy의 해당 기능은 transformers 4.12~4.28까지에서만 테스트되었습니다. 그 이후 버전에서 transformers의 변경이 발생하여 충돌이 생긴듯한데요, 추후 업데이트에서 수정하도록 하겠습니다!
그 전에 사용하시려거든 transformers를 4.28로 다운그레이드하시는걸 권장드립니다.

**Comment by bab2min** [comment]
@KKang29 
kiwipiepy 0.17.0에서 해당 문제 해결되어 이제 `transformers>4.28`에서도 잘 동작합니다.
다시 한번 버그 제보에 감사드립니다~

**Comment by KKang29** [comment]
@bab2min 
해결해주셔서 감사합니다~!!
